name: analogue_shifts_mobile
description: "A Recruitment and Technical Support Platform."
publish_to: 'none'
#version: 1.0.0+1
version: 1.0.3+3

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  lottie: ^3.1.0
  flutter_screenutil: ^5.9.0
  go_router: ^13.2.0
  intl: ^0.18.1
  logger: ^2.1.0
  flutter_svg: ^2.0.10+1
  flutter_animate: ^4.5.0
  gap: ^3.0.1
  dio: ^5.4.2+1
  get_it: ^7.6.7
  equatable: ^2.0.5
  dartz: ^0.10.1
  json_annotation: ^4.8.1
  provider: ^6.1.2
  hive: ^2.2.3
  top_snackbar_flutter: ^3.1.0
  awesome_snackbar_content: ^0.1.3
  hive_flutter: ^1.1.0
  googleapis: ^13.1.0
  google_sign_in: ^6.2.1
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.6
  device_info_plus: ^10.1.0
  internet_connection_checker_plus: ^2.3.0
  firebase_core: ^2.30.1
  firebase_messaging: ^14.9.1
  flutter_local_notifications: ^17.1.0
  otp_text_field: ^1.1.3
  image_picker: ^1.1.1
  awesome_dio_interceptor: ^1.2.0
  logo_n_spinner: ^0.1.6
  flutter_launcher_icons: ^0.13.1
  rename_app: ^1.3.2
  flutter_widget_from_html: ^0.15.0
  flutter_cache_manager: ^3.3.2
  webview_flutter: ^4.7.0
  change_app_package_name: ^1.1.0
  flutter_quill: ^9.3.11
  upgrader: ^10.3.0
  animated_icon: ^0.0.9
  iconsax: ^0.0.8
  in_app_review: ^2.0.9
  quill_html_editor: ^2.2.8
  shimmer: ^3.0.0
  firebase_crashlytics: ^3.5.7
  flutter_secure_storage: ^4.2.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher_icon.png"
  min_sdk_android: 21 
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - .env

  fonts:
     - family: JakertaSans
       fonts:
         - asset: assets/fonts/PlusJakartaSans-Italic-VariableFont_wght.ttf
         - asset: assets/fonts/PlusJakartaSans-VariableFont_wght.ttf
